#!/usr/bin/env python

import sys
sys.path.insert(1, '/usr/local/lib64/python3.4/site-packages')

from vypyr.application import Application

if __name__ == "__main__":
    app = Application(package="vypyr", version="0.1")
    app.run()
